### ISSUE TITLE
gulp-minify-css is deprecated

### ISSUE THREAD

**Issue by cxoltero** [kenzanlabs/pipeline-minify-css#17]
gulp-minify-css is deprecated, update to use gulp-minify-css.
this would be a good time to also update other dependencies

Dependency | Pipeline Version | Current Version
------------- | ---------------- | ----------------
Gulp-concat  |  2.6.0                  |     2.6.1
gulp-if            |     2.0.0               |     2.0.2
gulp-minify-css   |     1.2.1          |  (deprecated  use gulp-clean-css)
gulp-sourcemaps | 1.6.0            | 2.2.3

Dev deps:

Dependency  | Pipeline Version | Current Version
------------- | ---------------- | ----------------
Chai               | 3.3.0                     |  3.5.0
gulp               | 3.9.0                     | 3.9.1
pipeline-test-node | 1.0.1            | 1.1.1
pipeline-validate-js | 1.0.0-rc3   | 1.0.0-rc4

@bsawyer @paul-barry-kenzan @obuckley-kenzan is there any objection to update any of these dependencies?

**Comment by obuckley-kenzan** [comment]
I don't see much harm, as long as we can verify everything works the same (output, feature, etc).  the only concern I see is sourcemaps, which according to semver, is one breaking changes ahead
1.6 -> 2.2.3
